"""
Run this script carefully;. This script is used to rename the map csv files generated by TileMap.
"""
import os
import pandas as pd
from glob import glob

os.chdir('environment/frontend_server/static_dirs/assets/city/matrix/maze')
csv_files = glob("*.csv")

# To delete all csv files
# for file_path in csv_files:
#     os.remove(file_path)

# To rename all csv files
for file_path in csv_files:
    new_file_path = file_path.split('.')[0]
    new_file_path = new_file_path.split('_')[1].lower()
    new_file_path = new_file_path+'_maze.csv'
    os.rename(file_path, new_file_path)
